proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
  specs:
  - id: app1
    display-name: App 1
    #docker-cmd: ["R", "-e shiny::runApp('/root/app')"]
    docker-image: app1
    container-network: sp-example-net
    #container-volumes: ["/home/andrea/dev/shinyproxy/data:/root/data"]
    container-volumes: ["/root:/root/data"]

logging:
  file:
    shinyproxy.log
